-- ============================================================
-- Utility Provider API skeleton
-- External service providers (Főtáv, waterworks, gas, etc.)
-- can push announcements and request meter readings via REST.
-- ============================================================

-- ── 1. Extend announcements with utility-provider metadata ──────────────────
--    These columns are nullable so existing rows are unaffected.

ALTER TABLE announcements
  ADD COLUMN IF NOT EXISTS provider_type      text
    CHECK (provider_type IN ('heating','water','gas','electricity','telecom','other')),
  ADD COLUMN IF NOT EXISTS announcement_type  text DEFAULT 'general'
    CHECK (announcement_type IN ('reading_visit','service_start','service_stop','maintenance','general')),
  ADD COLUMN IF NOT EXISTS scheduled_at       timestamptz,
  ADD COLUMN IF NOT EXISTS external_ref       text;   -- provider's own reference ID

COMMENT ON COLUMN announcements.provider_type     IS 'Utility provider category (null for non-utility announcements)';
COMMENT ON COLUMN announcements.announcement_type IS 'What kind of utility event this is';
COMMENT ON COLUMN announcements.scheduled_at      IS 'When the utility event is scheduled to happen';
COMMENT ON COLUMN announcements.external_ref      IS 'Provider-supplied reference / event ID';

-- ── 2. Utility reading requests ─────────────────────────────────────────────
--    A provider tells residents to submit their meter by a deadline.

CREATE TABLE IF NOT EXISTS utility_reading_requests (
  id            uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  building_id   uuid        NOT NULL REFERENCES buildings(id) ON DELETE CASCADE,
  provider_name text        NOT NULL,
  provider_type text        NOT NULL
    CHECK (provider_type IN ('heating','water','gas','electricity','telecom','other')),
  meter_type    text        NOT NULL
    CHECK (meter_type IN ('viz','gaz','villany','ho','egyeb')),
  title         text        NOT NULL,
  description   text,
  deadline_at   timestamptz NOT NULL,
  external_ref  text,
  -- announcement auto-created when request is received
  announcement_id uuid      REFERENCES announcements(id) ON DELETE SET NULL,
  active        boolean     NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE utility_reading_requests IS
  'A provider asks residents to submit meter readings by deadline_at';

CREATE INDEX IF NOT EXISTS idx_utility_reading_requests_building
  ON utility_reading_requests (building_id, active, deadline_at DESC);

-- ── 3. Link meter_readings rows to the request that prompted them ───────────

ALTER TABLE meter_readings
  ADD COLUMN IF NOT EXISTS request_id uuid REFERENCES utility_reading_requests(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_meter_readings_request_id
  ON meter_readings (request_id) WHERE request_id IS NOT NULL;

-- Also extend meter_type to include heat ('ho') and catch-all ('egyeb').
-- We drop+recreate the check constraint (name generated by Postgres is table_col_check).
DO $$
BEGIN
  -- Drop old constraint if it exists
  ALTER TABLE meter_readings DROP CONSTRAINT IF EXISTS meter_readings_meter_type_check;
  -- Add extended constraint
  ALTER TABLE meter_readings ADD CONSTRAINT meter_readings_meter_type_check
    CHECK (meter_type IN ('viz','gaz','villany','ho','egyeb'));
EXCEPTION WHEN others THEN
  NULL; -- ignore: constraint may already be updated
END;
$$;

-- ── 4. Provider API tokens ───────────────────────────────────────────────────
--    TODO (skeleton): real validation stores hashed tokens here.
--    For now the route accepts any non-empty X-Provider-Token header.

CREATE TABLE IF NOT EXISTS utility_provider_tokens (
  id            uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  building_id   uuid        NOT NULL REFERENCES buildings(id) ON DELETE CASCADE,
  provider_name text        NOT NULL,
  provider_type text        NOT NULL,
  token_hash    text        NOT NULL UNIQUE,   -- SHA-256 / bcrypt of the raw token
  active        boolean     NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now(),
  last_used_at  timestamptz
);

COMMENT ON TABLE utility_provider_tokens IS
  'Hashed API tokens for external utility providers. One token per provider per building.';

CREATE INDEX IF NOT EXISTS idx_utility_provider_tokens_building
  ON utility_provider_tokens (building_id, active);

-- ── 5. RLS ───────────────────────────────────────────────────────────────────

ALTER TABLE utility_reading_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE utility_provider_tokens  ENABLE ROW LEVEL SECURITY;

-- Reading requests: building members can read
DROP POLICY IF EXISTS "Building members read utility_reading_requests" ON utility_reading_requests;
CREATE POLICY "Building members read utility_reading_requests"
  ON utility_reading_requests FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM memberships m
      WHERE m.building_id = utility_reading_requests.building_id
        AND m.profile_id  = auth.uid()
        AND m.active      = true
    )
  );

-- Insert via service role only (API routes run server-side)
DROP POLICY IF EXISTS "Service role insert utility_reading_requests" ON utility_reading_requests;
CREATE POLICY "Service role insert utility_reading_requests"
  ON utility_reading_requests FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Service role update utility_reading_requests" ON utility_reading_requests;
CREATE POLICY "Service role update utility_reading_requests"
  ON utility_reading_requests FOR UPDATE
  USING (true);

-- Provider tokens: managers only
DROP POLICY IF EXISTS "Managers read utility_provider_tokens" ON utility_provider_tokens;
CREATE POLICY "Managers read utility_provider_tokens"
  ON utility_provider_tokens FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM memberships m
      WHERE m.building_id = utility_provider_tokens.building_id
        AND m.profile_id  = auth.uid()
        AND m.active      = true
        AND m.role IN ('kozos_kepviselo','megbizott')
    )
  );

DROP POLICY IF EXISTS "Service role manage utility_provider_tokens" ON utility_provider_tokens;
CREATE POLICY "Service role manage utility_provider_tokens"
  ON utility_provider_tokens FOR ALL
  WITH CHECK (true);
